name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: clcollins/fork-sync@v1.6.3
        with:
          owner: clcollins
          base: master
          head: master
